name: medical_chart
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_zoom_drawer: ^1.0.4
  percent_indicator: ^2.1.8
  video_player: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.10.0
  flutter_local_notifications: ^3.0.2
  uuid: ^2.2.2
  flutter_svg: ^0.19.2
  flutter_screenutil: ^3.2.0
  intl: ^0.16.1
  cached_network_image: ^2.4.1
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  get_it: ^5.0.1
  fluttertoast: ^7.1.5
  flare_flutter: ^2.0.6
  package_info: ^0.4.3+2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/sample_medical_doctors.jpg
    - assets/images/medical_alert.png
    - assets/images/baby_sleep.png
    - assets/images/alert.svg


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/medical_chart_icon.jpg"
  adaptive_icon_background: "#f33c35"
  adaptive_icon_foreground: "assets/icons/medical_chart_icon.jpg"
